# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
}

provider "kubernetes" {
  # config_path = "./ip-recorder-us-east-1.k8s.local.config"
}

provider "helm" {
  kubernetes {
    config_path = "./ip-recorder-us-east-1.k8s.local.config"
  }
}
