# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "us-east-1"
}

provider "kubernetes" {
  config_path = "/home/aurora-2/.kube/eksctl/clusters/ip-recorder"
}

provider "helm" {
  kubernetes {
  config_path = "/home/aurora-2/.kube/eksctl/clusters/ip-recorder"
  }
}
